[metadata]
name = oft
version = 0.1.0
description = Object-level fusion transformer for TruckScenes

[options]
zip_safe = False
install_requires =
    truckscenes-devkit[all]>=1.0.0
    torch>=1.13.0
    torchvision>=0.14.0
    numpy==1.23.5
    pyquaternion>=0.9.9
    opencv-python-headless>=4.5.5.64
    Pillow>=9.0.0
    matplotlib>=3.5.1
    tqdm>=4.64.0
    scipy>=1.7.0
    pyyaml>=6.0

packages = find:
package_dir =
    = src

[options.packages.find]
where = src